[package]
name = "cargo_fetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo = "0.68.0"
url = "2.3.1"
semver = "1.0.16"
